### ISSUE TITLE
Start signing git commits

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#109]
See https://help.github.com/articles/signing-commits-with-gpg/

**Comment by rm-hull** [comment]
Curious how this will work if, say, I merge your branch and squash your signed commits via github's webpage?

**Comment by thijstriemstra** [comment]
@rm-hull that's what brought this signing to my attention: when you squash using github a box appears saying 'verified' appears next to the commit because it's signed (using github's pgp key).

**Comment by thijstriemstra** [comment]
![pgp-github](https://user-images.githubusercontent.com/305679/32299687-c8cb62a0-bf56-11e7-8442-0301ac419f16.png)

**Comment by rm-hull** [comment]
I just retagged luma.oled 2.3.0 

![image](https://user-images.githubusercontent.com/1915543/32299885-180e5c94-bf4f-11e7-9e58-6cc98f8effe1.png)

**Comment by rm-hull** [comment]
Now to try and work out how to have one GPG key across all my computers ...

**Comment by thijstriemstra** [comment]
I can image you can add multiple, just like SSH keys..

**Comment by thijstriemstra** [comment]
And new contributors do not need to worry because we're the one merging (and signing).

**Comment by thijstriemstra** [comment]
I've also enabled it.
