### ISSUE TITLE
[question] interactive menu

### ISSUE THREAD

**Issue by Stefal** [rm-hull/luma.core#112]
Hi !
I'm looking for a  way to write an interactive menu on a lcd screen connected to an arduino. Something like this one : https://www.youtube.com/watch?v=ak5TsUFhyf8
As I didn't see any component for menu items, is luma a good library to start with ?  My python skills are limited.

**Comment by rm-hull** [comment]
All that the luma library does really is twofold:
* provides a mechanism for displaying a PIL image - it translates that to the correct commands/data for the initialized display device
* give you a PIL-based drawing canvas that is sized for the screen you have initialized. All the drawing and text rendering capabilities are those in [ImageDraw](http://pillow.readthedocs.io/en/4.3.x/reference/ImageDraw.html).

So the short answer is yes (IMHO) - it is a good place to start, but in actual fact, you would be doing most of the graphics drawing using PIL methods.
