### ISSUE TITLE
[Question] Are "del" calls in "canvas" (render.py) actually required?

### ISSUE THREAD

**Issue by CRImier** [rm-hull/luma.core#123]
Hi! We're using luma.oled library in ZPUI, and it's a great success so far. However, the `luma`-provided `canvas` was constraining us, so [we did our own implementation](https://github.com/ZeroPhone/ZPUI/blob/devel/ui/canvas.py), based off `PIL.Image` and `PIL.ImageDraw` directly. We, of course, used [your `canvas` implementation](https://github.com/rm-hull/luma.core/blob/master/luma/core/render.py) as a reference.

So, a question about your `canvas` implementation - [on line 45](https://github.com/rm-hull/luma.core/blob/master/luma/core/render.py#L45), `del` is used - what's the reasoning behind it? Is the `draw` object not collected by GC eventually (IIRC Python can deal with cycling references quite well)?

**Comment by rm-hull** [comment]
If you look at http://pillow.readthedocs.io/en/5.0.0/reference/ImageDraw.html:

![screen shot 2018-02-13 at 09 32 23](https://user-images.githubusercontent.com/1915543/36154900-d676bd32-10a0-11e8-97a5-21bae1de27f2.png)

Then it shows in the example that you should delete the `draw` object afterwards. 

You should direct your question to the Pillow maintainers as to the exact reason this is necessary, but I imagine that it does some cleanup of underlying resources (much like one should always close an open file descriptor).

**Comment by CRImier** [comment]
Thank you!
