### ISSUE TITLE
SEG7_FONT up side down

### ISSUE THREAD

**Issue by DJJo14** [rm-hull/luma.core#129]
#### Type of Raspberry Pi
RPI1B (not plus)

#### Linux Kernel version
4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l GNU/Linux

#### Expected behaviour
Display is showing the time and is made at 19:12:32

![image](https://user-images.githubusercontent.com/5787161/37983194-05d9d80c-31f3-11e8-9d6c-c91fa6d38dac.png)

#### Actual behaviour
the numbers 96752 are upsite down, does not happen with other fonts

### Running code
```python
from luma.core.interface.serial import spi, noop
from luma.core.render import canvas
from luma.led_matrix.device import max7219
from luma.core.legacy.font import proportional, LCD_FONT, CP437_FONT, TINY_FONT, SINCLAIR_FONT, SEG7_FONT
from luma.core.legacy import text
import time
import datetime

serial = spi(port=0, device=0, gpio=noop())
device = max7219(serial, cascaded=5, block_orientation=-90)
while 1:
        with canvas(device) as draw:
                now = datetime.datetime.now()
                t = now.strftime('%H:%M:%S')
                text(draw, (0, 0), t, fill="white", font=(SEG7_FONT))
        time.sleep(0.1)
```

**Comment by thijstriemstra** [comment]
@DJJo14 have you tried adjusting the `block_orientation` to a different value?

**Comment by rm-hull** [comment]
I'll check locally with the emulator & write a little script to correct the values in the source code.

cc: @jonathanrjpereira

**Comment by jonathanrjpereira** [comment]
@DJJo14 Try changing the `block_orientation` to either `0` or `90` instead of `-90`.

**Comment by DJJo14** [comment]
thanks all for the fast replay, but it is not the block_orientation because when i change the font the orientation is correct.
![image](https://user-images.githubusercontent.com/5787161/37986936-2fd9e584-31fd-11e8-9d9a-9a679d0b4a8d.png)

**Comment by rm-hull** [comment]
I tried on the emulator and can confirm SEG7_FONT is indeed upside down. I thought it probably was based on @DJJo14 comments:

> the numbers 96752 are upsite down, does not happen with other fonts

Fix forthcoming ...
