### ISSUE TITLE
Disable travis cron jobs

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#143]
@rm-hull can you disable the cron job for travis for each project? you can do it in the travis settings for each project. It's generating annoying email notifications about outdated code.

**Comment by rm-hull** [comment]
The thing is - the travis cron jobs flag up when stuff breaks because dependencies change underneath us: https://travis-ci.org/rm-hull/luma.oled/jobs/405995283

**Comment by thijstriemstra** [comment]
Good point; they're actually quite useful here.
