### ISSUE TITLE
Something like luma.core.interface.serial.dummy - for tests?

### ISSUE THREAD

**Issue by CRImier** [rm-hull/luma.core#150]
I'm thinking about covering my `luma.core`-based drivers with tests. However, our test environment won't have real hardware accessible for testing. Any practice you'd suggest?

**Comment by thijstriemstra** [comment]
@CRImier have you checked the luma.core tests? e.g. https://github.com/rm-hull/luma.core/blob/master/tests/test_dummy.py

**Comment by CRImier** [comment]
oh, I see now, thank you! Seems like I confused it with what'd be a `dummy` display driver.

**Comment by CRImier** [comment]
Wait, no. The `dummy` interface seems to indeed be a dummy display, I'm interested in a dummy *interface* which I could then pass to constructors like `ssd1306`, `sh1106` etc. Any ideas?

**Comment by thijstriemstra** [comment]
@CRImier maybe https://github.com/rm-hull/luma.oled/blob/master/tests/helpers.py#L14?

**Comment by CRImier** [comment]
Passing `mock.Mock()` works. If there aren't any problems with this, feel free to close.

**Comment by CRImier** [comment]
oh, I see. Why use `unsafe=True`?

**Comment by thijstriemstra** [comment]
@CRImier I can see how a dummy serial device for testing is useful for users of luma.core. Let's see what @rm-hull has to say.

**Comment by rm-hull** [comment]
I'd be inclined to use `mock.Mock()` as you have discovered... 

As to `unsafe=True`: there was a specific PR (https://github.com/rm-hull/luma.oled/pull/72) to fix an issue (https://github.com/rm-hull/luma.oled/issues/55) where it was causing problems.
