### ISSUE TITLE
Control individual segments

### ISSUE THREAD

**Issue by mb720** [rm-hull/luma.core#168]
Hi and thanks a lot for luma!

I'd like to turn on and off individual segments of my seven segment display¹.

Browsing luma's source code, I think the `point` method is my best bet at the moment, it's called [here](https://github.com/rm-hull/luma.core/blob/b54f3266f59b5fd8c01a1f318319975dea44ecfc/luma/core/virtual.py#L553).

It seems to be a member of [`canvas`](https://github.com/rm-hull/luma.core/blob/b54f3266f59b5fd8c01a1f318319975dea44ecfc/luma/core/render.py#L8) but I don't see `point` defined there.

My question is: Where is `point` defined? Or is this a red herring if my goal is to control individual segments?

Thanks again for your work!

---
¹ [These](https://www.amazon.co.uk/MakerHawk-8-Digit-Segment-MAX7219-Supports/dp/B07CKSKNGW) are the ones I have specifically. It says MAX2719CWG 1852 on the chip at the back.

**Comment by rm-hull** [comment]
The canvas will give you back an instance of pillows [ImageDraw](https://pillow.readthedocs.io/en/latest/reference/ImageDraw.html), so you can utilize any method that it exposes.

All that canvas really does is initialize an image of the correct dimensions for the display, it then gives you a drawing surface, and then when the with block exits, it makes sure that the image you drew onto is sent to the display.
