### ISSUE TITLE
Latest release listing is old

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#182]
Looking at the homepage, there is a really old release listed as latest:

<img width="272" alt="Screenshot 2020-08-10 at 22 48 10" src="https://user-images.githubusercontent.com/305679/89829913-a7168800-db5b-11ea-82ab-2964cc8bd0f9.png">

**Comment by rm-hull** [comment]
I think I must’ve manually created a release for 1.0.0

It’s now showing 68 tags and when you click through it takes you to the latest

**Comment by thijstriemstra** [comment]
Much better.
