### ISSUE TITLE
LCD ST7735 128X128  - WHITE SCREEN

### ISSUE THREAD

**Issue by gigabauertech** [rm-hull/luma.core#187]
Hello guys how are you all doing? Its my first time ever using GitHub so I'm sorry if I'm not using the right place to find an answer to my problem. 

#### Type of Raspberry Pi and LCD specifications
Raspberry Pi 3B+
ST7735 LCD SPI 1.44 128x128

Place where I bought the LCD:
[https://www.aliexpress.com/item/GREATZT-1PCS-5V-3-3V-1-44-inch-TFT-LCD-Display-Module-128-128-Color-Sreen/32948378014.html?spm=a2g0s.9042311.0.0.1f614c4dALAgbo](url)

#### Linux Kernel version
Linux retropie 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
Library: luma.lcd 1.1.0 (luma.core 1.8.3)
Python-dev: 2.7.13-2
Python-pip: 9.0.1-2+rpt2

#### Expected behaviour
I am willing to use this LCD to show at full time all the status of my Raspberry. Such as the cpu temp, storage, IP address and etc. My plan is to make this script start up as soon as my rasp starts too. So I created a sh file to be triggered by the rc.local all the time it boots up. 

My gpio set up is just like the library document:
led 18
sck 11(sclk)
sda 10(mosi)
ao 23
reset 24
cs 8(ceo)
gnd
vcc 3.3/5

This is how it looks whenever it works:
![image](https://user-images.githubusercontent.com/45311455/51804422-dac6e100-2247-11e9-9361-0a04185cee6b.png)

This is my status script: https://paste.ofcode.org/LuY4CDcwSmMcXjGzUBjXx

This is the sh script witch the rc.local triggers when the rasp boots up:
![image](https://user-images.githubusercontent.com/45311455/51804473-9ab42e00-2248-11e9-86fd-239bd0e8344c.png)

#### Actual behaviour
My actual problem is that sometimes the LCD will turn on but completely white. Even if you check it closer you won't be able to see anything or even blinking. 

![image](https://user-images.githubusercontent.com/45311455/51804518-1a41fd00-2249-11e9-89f8-063eccbb4d1c.png)

So, to make it work I go to the command line and and input:

![image](https://user-images.githubusercontent.com/45311455/51804502-e1098d00-2248-11e9-8e7c-a4753ed86399.png)

Even running this command in the manual way the screen will shows itself all white, so I have to interrupt and run again until it shows the status screen as I showed before.

I tried to play with those commands from the library such as the device.clean, decive.show however I will randomly get this white screen. 

Have you ever seen this type of issue? 

Note: I tried to change from the 3.3 to 5.0 but the problem is still the same.
Note_2: I also tried to wait a while to see if it would change but nothing happens the white screen will stay up until you interrupt.

In case I was not clear please let me know so I can even make a video. Thanks for this amazing library and also for the attention.

**Comment by sahasradal** [comment]
these cheap aliexpress clones have issues. please add a 4.7k pullup to CS pin of LCD and it works fine.
