### ISSUE TITLE
Use time.perf_counter_ns

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#204]
Python 3.7 introduces `time.monotonic_ns`. [PEP564](https://www.python.org/dev/peps/pep-0564/) explains the rationale but what stood out to me is:

> A server is running for longer than 104 days. A clock is read before and after running a function to measure its performance to detect performance issues at runtime. Such benchmark only loses precision because of the float type used by clocks, not because of the clock resolution.

> On Python microbenchmarks, it is common to see function calls taking less than 100 ns. A difference of a few nanoseconds might become significant.

More precision is always better.

**Comment by thijstriemstra** [comment]
thoughts @rm-hull? It could be introduced in 2.0 as well.

**Comment by rm-hull** [comment]
Yep, we can add this; was there anywhere specifically it would be useful - presumably updating existing instances of `time.monotic()` only?

**Comment by thijstriemstra** [comment]
yea my thoughts as well. I'll start a branch.

**Comment by thijstriemstra** [comment]
This can be easily supported once Python 3.6 reaches EOL.

**Comment by thijstriemstra** [comment]
> This can be easily supported once Python 3.6 reaches EOL.

looks like this happened on [23 Dec 2021](https://endoflife.date/python)

**Comment by thijstriemstra** [comment]
more good `time.sleep()` improvements in python 3.11: https://docs.python.org/3.11/whatsnew/3.11.html#time
