### ISSUE TITLE
luma.core should not introduce device specific code

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#21]
if an emulator does something different, keep it in it's respective package.

e.g. https://github.com/rm-hull/luma.core/blob/master/luma/core/emulator.py#L236 belongs in the led_matrix package..

**Comment by rm-hull** [comment]
Arguably, _all_ the emulator-specific stuff should be moved out of luma.core, into its own luma.emulator package which can have luma.core _and_ pygame as dependencies

**Comment by thijstriemstra** [comment]
Good plan!
