### ISSUE TITLE
Use github actions to publish to pypi

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#224]
See https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

**Comment by thijstriemstra** [comment]
@rm-hull I see you currently use this script: https://github.com/rm-hull/luma.core/blob/master/bin/make_release.sh

But basically now github actions would publish to pypi (using that command) whenever a new tag is created. This way it's as simple as creating a new tag and releasing can be done remotely.

Thoughts?

**Comment by rm-hull** [comment]
Great idea. Presumably all we need (aside from the action yaml) is the pypi creds stored as a secret in GitHub?

**Comment by thijstriemstra** [comment]
Yea follow [these instructions](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-environment) to create 2 secrets:

- `PYPI_USERNAME`
- `PYPI_PASSWORD`

Please let me know when you added these @rm-hull

**Comment by thijstriemstra** [comment]
@rm-hull actually scratch previous comment, this approach uses pypi API key which seems a better solution to me: https://github.com/marketplace/actions/pypi-publish

More info on pypi api: https://pypi.org/help/#apitoken

**Comment by rm-hull** [comment]
@thijstriemstra created

![B47A9FB9-0964-4FF8-A2C9-A2ADBED7AEF2](https://user-images.githubusercontent.com/1915543/105547093-0de8c180-5cf6-11eb-990a-18b9857bc2f1.png)
