### ISSUE TITLE
Unnecessary delete statement in function (identified with LGTM.com)

### ISSUE THREAD

**Issue by m-roberts** [rm-hull/luma.core#243]
https://github.com/rm-hull/luma.core/blob/e4e3623d2e374bde152f4703ff535c90e35dc232/luma/core/virtual.py#L171
triggers this rule:
https://lgtm.com/rules/1506104658325/

**Comment by thijstriemstra** [comment]
i'm not sure; might be a false positive, what do you think @rm-hull?

**Comment by rm-hull** [comment]
Sounds like it’s not necessary & can be removed. It might’ve be a hangover from py27 / PIL days
