### ISSUE TITLE
Add 4- & 8-bit parallel interfaces

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.core#41]
Somewhat related to https://github.com/rm-hull/luma.lcd/issues/19

Use RPi.GPIO to bit-bang out 4 or 8 bus lines according to the HD44780 datasheet spec. The interface should have the same "shape" as the existing [luma.core.interface.serial](https://github.com/rm-hull/luma.core/blob/master/luma/core/interface/serial.py) interfaces - i.e. implement `data()` and `command()` methods.

Also: ~~Move `luma.core.serial` to `luma.core.interface.serial` and add this new functionality to `luma.core.interface.parallel`. Various breaking changes to device implementations to rename `serial_interface=` constructor arg to `interface=`.~~ (done with #78)

<img width="616" alt="screen shot 2017-03-06 at 22 12 28" src="https://cloud.githubusercontent.com/assets/1915543/23632515/1767fcca-02ba-11e7-8d74-a9f636e806ba.png">

(screen grab from https://cdn-shop.adafruit.com/datasheets/HD44780.pdf)

**Comment by thijstriemstra** [comment]
> Move luma.core.serial to luma.core.interface.serial and add this new functionality to luma.core.interface.parallel. Various breaking changes to device implementations to rename serial_interface= constructor arg to interface=.

Let's add a proper DeprecationWarning when importing from the old location. The warning should also include the version nr when it'll be removed.
