### ISSUE TITLE
Add word-wrap capability to luma.core.virtual.terminal

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.core#42]
Currently, the terminal class will check that text to be rendered using proportional fonts wont overflow over the right hand edge. If there is not enough width to display the next character, it will insert a newline. For example:

![image](https://cloud.githubusercontent.com/assets/1915543/23633252/e8230b96-02bc-11e7-906b-106087abf275.png)

Add a constructor arg setting so that wrapping works at the word level, eg, the above string would render as

```
The quick brown fox
jumps over the lazy
dog
```

**Comment by thijstriemstra** [comment]
https://docs.python.org/3/library/textwrap.html looks useful here.

**Comment by thijstriemstra** [comment]
Should be fixed with #78:

![quick_brown_fox_word_wrap](https://cloud.githubusercontent.com/assets/305679/25068144/6fa2831e-225a-11e7-82f5-ab0093ed78a6.png)
