### ISSUE TITLE
Remove deprecated code in v1.0.0

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#51]
Now that #2 is fixed, we should remove the deprecated `bcm_DC` and `bcm_RST` arguments from the `spi` class somewhere before the version 1.0.0 release.

**Comment by thijstriemstra** [comment]
And remove deprecated luma.core.serial module (#41).

**Comment by thijstriemstra** [comment]
And there's also `luma/core/legacy`..

**Comment by thijstriemstra** [comment]
@rm-hull let's set a release date for 1.0.0? I think beginning/end september would be fine..?

**Comment by rm-hull** [comment]
Yep, lets go for that.
Possibly the same for led_matrix
