### ISSUE TITLE
Core docs

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#54]
Currently the same instructions to enable spi/i2c are duplicated across the various luma sub-projects. I think common docs like how to enable spi should be in the core docs, and device specific installation instructions belong in the specific sub-project docs.

**Comment by rm-hull** [comment]
Ok, maybe now is the right time to have a single docs site?  ... https://github.com/rm-hull/luma.docs

have added you as a collaborator ;-)

**Comment by thijstriemstra** [comment]
I guess it only needs a rtd site, no pypi stuff.

**Comment by rm-hull** [comment]
Yes think so

**Comment by rm-hull** [comment]
So, I just (mainly) copy & pasted the core `docs/` directory and created the rtd config - see https://luma-docs.readthedocs.io

Perhaps ought to think how to best structure the docs, but maybe document ideas & thoughts as issues in that repo.

hence, closing -this- issue
