### ISSUE TITLE
persistence of text on ssd1306

### ISSUE THREAD

**Issue by CelsoCaldeira** [rm-hull/luma.core#74]
I'm trying to write a python script that takes a string as parameter and shows it on the display.
but if I call a simple draw.text() it shows and turn it off the display, i mean, i need to import time and call a delay to see the msg, then the text goes away after the program exits.
My question is if there is some way to let the text on display after script ends?
I was reading about the set of statements with/as, and saw that they are made in a way it guarantees the end of the methods called, i could have understood wrong, but is there another way to call the method draw.text() not using 'with' and 'as'?
If this is not the best or known solution and someone could explain another way of achieve the goal of let the text on the display after the script finishes it's execution it will be great, any help is appreciated.
the device is an orange pi zero, and it's on i2c0, default address0x3c
Thanks in advance for any help!! 
Any additional info just ask i will provide asap.

**Comment by rm-hull** [comment]
There is no "official" way to do this, but you can override the cleanup method in the device to do nothing, as discussed here: https://github.com/rm-hull/luma.oled/issues/140
