### ISSUE TITLE
Terminal scrolling background issue

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#79]
Scrolling with the terminal when the background colour is not black is buggy - see the yellow bar at the bottom.

![ansi_colors_wrapped](https://cloud.githubusercontent.com/assets/305679/25072278/9be2f5c4-22ca-11e7-9371-20a91dc1d4fc.png)

**Comment by rm-hull** [comment]
Think this should be an easy fix: https://github.com/rm-hull/luma.core/blob/master/luma/core/virtual.py#L350 should use the `self._default_bgcolor` as the fill colour

**Comment by thijstriemstra** [comment]
Added PR that addresses this. Didn't change the value for the erase method because it broke the other tests/functionality.
