### ISSUE TITLE
Multiple I2C devices

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#8]
PCF8574 allows you to use multiple I2C devices ([example](http://www.rototron.info/using-an-i2c-lcd-display-with-a-raspberry-pi/)). Is this something that can be supported?

**Comment by rm-hull** [comment]
It is possible, as long as the I2C devices each have a unique I2C address. Sometimes there are 2 or 3 zero-ohm resisters which allow you to set the address, so you can run 3 of the same wthout clashes.

Same goes for SPI .. it is possible to support 2 devices per channel I think

**Comment by thijstriemstra** [comment]
Apparently Adafruit created [a special class](https://github.com/adafruit/Adafruit_Python_GPIO/blob/master/Adafruit_GPIO/PCF8574.py) for this.

**Comment by rm-hull** [comment]
Ah, right, gotcha - the 8574 is just an 8-bit IO expander, and that code is using it to serially clock data/commands into the 8574, and then latch the 8 bits all at once onto the parallel interface of a 1602 display - basically treating it as a glorified shift register.

They are often used to piggy back these displays: http://www.ebay.co.uk/itm/Serial-IIC-I2C-TWI-1602-16x2-LCD-Display-Module-for-Arduino-Raspberry-PI-/282269918634

![image](https://cloud.githubusercontent.com/assets/1915543/22225348/0c38817e-e1ba-11e6-86c4-b22a84354670.png)

This picture of the backside shows the tiny addon board (in black) with a 8574.

I had used a 1602 display coupled up to an MCP23017 (also I2C, but 16 I/O ports) a couple of years ago.

**Comment by thijstriemstra** [comment]
> serially clock data/commands into the 8574, and then latch the 8 bits all at once onto the parallel interface of a 1602 display 

Ah simple... :-O I'm gonna start with this and see how it goes ;) http://www.rototron.info/using-an-i2c-lcd-display-with-a-raspberry-pi/

**Comment by rm-hull** [comment]
These chips look interesting:
http://www.linear.com/product/LTC4316
http://www.linear.com/product/LTC4317
http://www.linear.com/product/LTC4318

So you could connect, say, two identical I2C-based SSD1306 128x64 screens to an LTC4317, and although they have the same address, the chip does address translation so they appear at addresses 0x3C and 0x3E

**Comment by rm-hull** [comment]
@thijstriemstra - please see updated comments on #55 
Can this issue be closed?

**Comment by thijstriemstra** [comment]
Yep.
