### ISSUE TITLE
Bit-banged serial interface?

### ISSUE THREAD

**Issue by combs** [rm-hull/luma.core#82]
Similar to #41, could be nice to have an alternative bit-banged GPIO interface for serial devices. I'm working on a project with a few screens on the same device, and being able to put a pcd8544 on gpio instead of hardware SPI would be a nice alternative to making all the hardware play nice together. 

Could also be a (slow) fallback for those who can't get hardware SPI or I2C running on their oddball systems.

No worries if this seems out of scope for luma!

**Comment by rm-hull** [comment]
There is already, see https://github.com/rm-hull/luma.core/pull/63

**Comment by combs** [comment]
oooo thank you!
