### ISSUE TITLE
Deprecate legacy code

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.core#96]
luma.core v1.0.0 was released but the `legacy` package still exists. Let's add a deprecation warning and/or note to the module(s) that it'll be removed eventually.

**Comment by thijstriemstra** [comment]
@rm-hull what's the deal with the legacy package? why is it still there/called like that?

**Comment by rm-hull** [comment]
Can't decide whether this should stay or go; there is definitely some utility in having fixed width font handling (esp. for low resolution LED matrix devices).... maybe it's just the negative connotation of the word _"legacy"_ ?

**Comment by thijstriemstra** [comment]
If there's doubt we should probably keep it, closing.
