### ISSUE TITLE
Travis builds on python 3.6 breaks.

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.core#98]
Have just experienced this on a branch, but is also happening on master (see https://travis-ci.org/rm-hull/luma.core/jobs/259461663#L313). This did build cleanly on master - it was green, restarted it, and now failing !

@thijstriemstra - any ideas/insight?

**Comment by thijstriemstra** [comment]
Well there's this https://github.com/pypa/setuptools/issues/1086, looking into it.

**Comment by rm-hull** [comment]
Maybe just upgrading travis's setuptools is the simple solution: https://github.com/labgrid-project/labgrid/pull/119/files

**Comment by thijstriemstra** [comment]
We're already doing that.

**Comment by thijstriemstra** [comment]
Your fix seems to have worked in #97.

**Comment by rm-hull** [comment]
See https://github.com/rm-hull/luma.core/pull/97/commits/58d672825d25f60749b7f603bb16495097697d4f
